### ISSUE TITLE
Ghost sucks

### ISSUE THREAD

**Issue by bwestmoreland** [NodeGreenville/nodegreenville#15]
As a developer I'm finding Ghost to be more and more painful to get working.  I think we may be better off removing ghost and setting up our own simple "Blog" or "CMS" as a learning exercise.

done when: 
- ghost is removed

**Comment by bwestmoreland** [comment]
As it turns out... ghost seems to be working for now, so we may tone this down and discuss it  a little bit.

**Comment by harrythree** [comment]
There still seems to be the issue with Ghost hijacking the CSS. If you go to the blog and then back home (and refresh), all of the styling is lost.

**Comment by bwestmoreland** [comment]
Yeah, it's not like it just hijacks the CSS, it appears it's only loading home.hbs without any of the other handlebars styling.

**Comment by trendsetter37** [comment]
I'll try a couple of things with this today. But yea I found myself saying "ghost sucks" a couple of times as well.
