### ISSUE TITLE
Bug: The events page unauthorized

### ISSUE THREAD

**Issue by bwestmoreland** [NodeGreenville/nodegreenville#16]
The 'events' link is throwing an error when running in staging and prod.

done when:

The events link loads a page.

**Comment by harrythree** [comment]
To fix this issue the environment variables for the Meetup API will need to be added to [Heroku](https://devcenter.heroku.com/articles/config-vars).

MEETUP_API=12345nodegreenvilleapikey
MEETUP_GROUP_NAME=NodeGreenville
