### ISSUE TITLE
Refactoring the Ghost blog to use Express for the base

### ISSUE THREAD

**Issue by bwestmoreland** [NodeGreenville/nodegreenville#7]
_From @blakeyoder on October 22, 2015 0:2_

done when:
- Express app that loads a 200 ;)
- Ghost mounted on /blog

_Copied from original issue: NodeGreenville/nodegreenville-ghost#11_

**Comment by bwestmoreland** [comment]
_From @trendsetter37 on October 26, 2015 13:9_

[This](https://github.com/TryGhost/Ghost/issues/827#issuecoment-52205649) looks 
doable.

More info [here](https://github.com/TryGhost/Ghost/wiki/Using-Ghost-as-an-NPM-module#example-customizations)

> Ghost's default index.js uses this feature to add subdirectory support to Ghost. It is possible to create a parent express instance, call .use to add your own middleware and configuration, and then tell the ghostServer to start Ghost with your new parent app.
> 
> ``` javascript
> 
> var ghost = require('ghost'),
>    express = require('express'),
>    parentApp = express();
> 
> ghost().then(function (ghostServer) {
>    parentApp.use(ghostServer.config.paths.subdir, ghostServer.rootApp);
> 
>    ghostServer.start(parentApp);
> });
> ```
> 
> In this snippet there are two express instances - parentApp can be your own express instance containing all of your own configuration and rootApp is the express instance you'll get from ghostServer which has all of Ghost's behaviour and configuration.
> 
> The line `parentApp.use(ghostServer.config.paths.subdir, ghostServer.rootApp);` mounts Ghost on a subdirectory inside the existing express app.
> 
> `ghostServer.config.paths.subdir` contains the subdirectory specified via the url property in config.js. For example, configuring url: 'http://localhost:2368/blog' will run Ghost under /blog. The property `ghostServer.config.paths.subdir` will equal /blog.
> 
> Note: If you pass an express instance to ghostServer.start which has not had the Ghost rootApp mounted on it (i.e. you haven't called .use()), then ghostServer will still start a server but it will not have Ghost's functionality.

**Comment by bwestmoreland** [comment]
_From @harrythree on October 29, 2015 0:27_

http://www.triplet.fi/blog/running-your-ghost-blog-and-express-app-on-heroku/

**Comment by trendsetter37** [comment]
Is it ok to move this to the done column?
