### ISSUE TITLE
Identify best host option for site

### ISSUE THREAD

**Issue by bwestmoreland** [NodeGreenville/nodegreenville#8]
_From @blakeyoder on October 22, 2015 0:9_

done whne:
- server is running...yay

_Copied from original issue: NodeGreenville/nodegreenville-ghost#12_

**Comment by bwestmoreland** [comment]
Server is running at nodegreenville.westmoreland.us.  That said, I am currently the only one with credentials and will be working on the deployment for this paired with continuous integration.

**Comment by bwestmoreland** [comment]
The app is now hosted on Heroku with two different options.
1. Staging - https://nodegreenville-staging.herokuapp.com when merged to DEV
2. Production - https://nodegreenville-prod.herokuapp.com when merged to PROD

Travis deploys the build automatically depending on which branch is committed to.

Postgres Database connect string is available in each environment via `process.env.DATABASE_URL`

**Comment by trendsetter37** [comment]
So is master our PROD branch?

**Comment by bwestmoreland** [comment]
Yes

—
